import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { exactCliInvocation } from "./bridges.mjs";
import { compareUtf8Bytes, parseSkillMetadata } from "./skills.mjs";

const require = createRequire(import.meta.url);
const manifest = require("./official-skills.json");
const DEFAULT_PACKAGE_ROOT = fileURLToPath(new URL("../../../", import.meta.url));
const MANIFEST_FORMAT = "dotaios-official-skill-manifest/v1";
const PACKAGE_FORMAT = "dotaios-official-skill-package/v1";
const NAME_RE = /^(?=.{1,64}$)[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SHA256_RE = /^[a-f0-9]{64}$/;
const VERSION_RE = /^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
const STRICT_UTF8 = new TextDecoder("utf-8", { fatal: true });
const POSIX_MODE_MASK = 0o7777;
// Windows exposes synthetic permission bits; the manifest still records the
// portable POSIX intent, while runtime ownership there is proved by type,
// link count, and bytes.
const ENFORCES_POSIX_MODES = process.platform !== "win32";

validateManifestShape(manifest);

export function officialSkillNames() {
  return manifest.skills.map(({ name }) => name);
}

export function officialSkillManifest() {
  return structuredClone(manifest);
}

export function materializeOfficialCandidateBytes(packedBytes, render, candidateVersion) {
  if (typeof candidateVersion !== "string" || !VERSION_RE.test(candidateVersion) || !validRender(render)) {
    throw officialPackageError("The official skill candidate authority is invalid.");
  }
  return materializeCandidateBytes(
    Buffer.from(packedBytes),
    render,
    manifest.candidate_version_placeholder,
    candidateVersion
  );
}

export function isRecognizedOfficialSkillOverlay(skillName, relativePath, bytes) {
  if (skillName !== "plan-today" || relativePath !== "prompt.md") return false;
  if (bytes?.[0] === 0xef && bytes?.[1] === 0xbb && bytes?.[2] === 0xbf) return false;
  let text;
  try {
    text = STRICT_UTF8.decode(bytes);
  } catch {
    return false;
  }
  const guidance = [
    "This file is generated by DotAIOS. Re-run `npx dotaios interview` to refresh it.",
    "This file is generated by DotAIOS. The candidate version was unavailable, so it contains no runnable refresh command."
  ];
  const lines = text.split("\n");
  const generatedLine = lines[2] || "";
  if (
    !guidance.includes(generatedLine)
    && !/^This file is generated by DotAIOS\. Re-run `npx(?:\.cmd)? dotaios@[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)? interview` to refresh it\.$/.test(generatedLine)
  ) return false;
  return /^# plan-today personalization\n\n[^\n]+\nSkills should prefer this compiled file over reading the individual context files\.\n\n## Who you are\n[^\r\n]+\n\n## What you're working on\n[\s\S]*?\n\n## What matters this week\n[\s\S]*?\n\n## Planning preferences\n- Plan style: [^\r\n]*\n- Priorities per day: [^\r\n]*\n- Time blocks: [^\r\n]*\n- Frog definition: [^\r\n]*\n$/.test(text);
}

export async function loadOfficialSkillPackage({
  packageRoot = DEFAULT_PACKAGE_ROOT,
  candidateVersion
} = {}) {
  const root = path.resolve(packageRoot);
  const version = candidateVersion === undefined
    ? await readPackageVersion(root)
    : candidateVersion;
  const candidateInvocation = exactCliInvocation(version);
  const skillsRoot = path.join(root, "skills");
  await validatePackedInventory(skillsRoot);

  const skills = [];
  for (const declaredSkill of manifest.skills) {
    const sourceRoot = path.join(skillsRoot, declaredSkill.name);
    const rootStats = await fs.lstat(sourceRoot);
    if (
      !rootStats.isDirectory()
      || rootStats.isSymbolicLink()
      || (ENFORCES_POSIX_MODES && (rootStats.mode & POSIX_MODE_MASK) !== declaredSkill.mode)
    ) throw officialPackageError(`Packed official skill root drifted: ${declaredSkill.name}`);

    const packedEntries = await fs.readdir(sourceRoot, { withFileTypes: true });
    const packedNames = packedEntries.map(({ name }) => name).sort(compareUtf8Bytes);
    const declaredNames = declaredSkill.files.map(({ path: relative }) => relative);
    if (!sameStringArray(packedNames, declaredNames)) {
      throw officialPackageError(`Packed official skill inventory drifted: ${declaredSkill.name}`);
    }

    const files = [];
    for (const declaredFile of declaredSkill.files) {
      const sourcePath = path.join(sourceRoot, declaredFile.path);
      const stats = await fs.lstat(sourcePath);
      if (
        !stats.isFile()
        || stats.isSymbolicLink()
        || stats.nlink !== 1
        || (ENFORCES_POSIX_MODES && (stats.mode & POSIX_MODE_MASK) !== declaredFile.mode)
      ) throw officialPackageError(`Packed official file mode or type drifted: ${declaredSkill.name}/${declaredFile.path}`);
      const packedBytes = await fs.readFile(sourcePath);
      if (
        packedBytes.length !== declaredFile.bytes
        || sha256(packedBytes) !== declaredFile.packed_sha256
      ) throw officialPackageError(`Packed official file bytes drifted: ${declaredSkill.name}/${declaredFile.path}`);

      const installedBytes = materializeOfficialCandidateBytes(packedBytes, declaredFile.render, version);
      files.push({
        path: declaredFile.path,
        mode: declaredFile.mode,
        bytes: installedBytes.length,
        packed_bytes: Buffer.from(packedBytes),
        packed_sha256: declaredFile.packed_sha256,
        installed_bytes: installedBytes,
        installed_sha256: sha256(installedBytes),
        render: structuredClone(declaredFile.render),
        predecessors: Object.entries(declaredFile.accepted_predecessors).map(([release, predecessor]) => ({
          release,
          mode: predecessor.mode,
          sha256: predecessor.sha256
        }))
      });
    }

    const instructions = files.find(({ path: relative }) => relative === "SKILL.md");
    const metadata = parseSkillMetadata(STRICT_UTF8.decode(instructions.installed_bytes));
    skills.push({
      name: declaredSkill.name,
      mode: declaredSkill.mode,
      source_path: sourceRoot,
      generated_overlays: structuredClone(declaredSkill.generated_overlays),
      files,
      catalog: {
        dir: declaredSkill.name,
        name: metadata.name || declaredSkill.name,
        description: metadata.description,
        triggers: metadata.triggers,
        whenToUse: metadata.whenToUse
      }
    });
  }

  return {
    format: PACKAGE_FORMAT,
    manifest_format: MANIFEST_FORMAT,
    package_root: root,
    candidate_version: version,
    candidate_invocation: candidateInvocation,
    skills
  };
}

function validateManifestShape(value) {
  if (
    !value || typeof value !== "object" || Array.isArray(value)
    || value.format !== MANIFEST_FORMAT
    || value.candidate_version_placeholder !== "<exact-candidate-version>"
    || !Array.isArray(value.supported_predecessors)
    || !sameStringArray(value.supported_predecessors, ["2.0.8", "2.0.9", "2.0.10", "2.0.11"])
    || !Array.isArray(value.skills)
  ) throw officialPackageError("The bundled official skill manifest is invalid.");

  let previousName = null;
  for (const skill of value.skills) {
    if (
      !skill || typeof skill !== "object" || Array.isArray(skill)
      || !NAME_RE.test(skill.name || "")
      || (previousName !== null && compareUtf8Bytes(previousName, skill.name) >= 0)
      || skill.mode !== 0o755
      || !Array.isArray(skill.files) || skill.files.length === 0
      || !Array.isArray(skill.generated_overlays)
    ) throw officialPackageError("The bundled official skill manifest is invalid.");
    previousName = skill.name;

    const coordinates = new Set();
    let previousPath = null;
    for (const file of skill.files) {
      validateRelativeLeaf(file?.path);
      if (
        coordinates.has(file.path)
        || (previousPath !== null && compareUtf8Bytes(previousPath, file.path) >= 0)
        || file.mode !== 0o644
        || !Number.isSafeInteger(file.bytes) || file.bytes < 0
        || !SHA256_RE.test(file.packed_sha256 || "")
        || !validRender(file.render)
        || !sameStringArray(Object.keys(file.accepted_predecessors || {}), value.supported_predecessors)
      ) throw officialPackageError("The bundled official skill manifest is invalid.");
      previousPath = file.path;
      coordinates.add(file.path);
      for (const predecessor of Object.values(file.accepted_predecessors)) {
        if (predecessor?.mode !== 0o644 || !SHA256_RE.test(predecessor.sha256 || "")) {
          throw officialPackageError("The bundled official skill manifest is invalid.");
        }
      }
    }
    if (!coordinates.has("SKILL.md")) {
      throw officialPackageError("The bundled official skill manifest is invalid.");
    }
    for (const overlay of skill.generated_overlays) {
      validateRelativeLeaf(overlay?.path);
      if (
        coordinates.has(overlay.path)
        || overlay.kind !== "interview-plan-today-prompt/v1"
        || overlay.mode !== 0o644
        || skill.name !== "plan-today"
        || overlay.path !== "prompt.md"
      ) throw officialPackageError("The bundled official skill manifest is invalid.");
      coordinates.add(overlay.path);
    }
  }
}

async function validatePackedInventory(skillsRoot) {
  const entries = await fs.readdir(skillsRoot, { withFileTypes: true });
  const names = entries.map(({ name }) => name).sort(compareUtf8Bytes);
  if (!sameStringArray(names, officialSkillNames())) {
    throw officialPackageError("Packed official skill inventory drifted.");
  }
  if (entries.some((entry) => !entry.isDirectory() || entry.isSymbolicLink())) {
    throw officialPackageError("Packed official skill inventory contains an unsafe entry.");
  }
}

function materializeCandidateBytes(bytes, render, placeholder, version) {
  if (render.kind === "verbatim") return Buffer.from(bytes);
  if (bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
    throw officialPackageError("Candidate-rendered official instructions must not contain a UTF-8 BOM.");
  }
  let text;
  try {
    text = STRICT_UTF8.decode(bytes);
  } catch {
    throw officialPackageError("Candidate-rendered official instructions are not UTF-8.");
  }
  const observedCount = text.split(placeholder).length - 1;
  if (observedCount !== render.token_count) {
    throw officialPackageError("Candidate token count drifted in packed official instructions.");
  }
  const materialized = text.replaceAll(placeholder, version);
  if (materialized.includes(placeholder) || /\bnpx(?:\.cmd)?\s+dotaios(?!@)/.test(materialized)) {
    throw officialPackageError("Official instructions contain an unpinned DotAIOS invocation.");
  }
  return Buffer.from(materialized, "utf8");
}

async function readPackageVersion(packageRoot) {
  let value;
  try {
    const bytes = await fs.readFile(path.join(packageRoot, "package.json"));
    if (bytes.length > 64 * 1024) throw new Error("oversize");
    value = JSON.parse(STRICT_UTF8.decode(bytes)).version;
  } catch {
    throw officialPackageError("Could not read the official skill package version.");
  }
  if (typeof value !== "string" || !VERSION_RE.test(value)) {
    throw officialPackageError("The official skill package version is invalid.");
  }
  return value;
}

function validRender(render) {
  if (!render || typeof render !== "object" || Array.isArray(render)) return false;
  if (render.kind === "verbatim") return Object.keys(render).length === 1;
  return render.kind === "exact-candidate-version/v1"
    && Number.isSafeInteger(render.token_count)
    && render.token_count > 0
    && Object.keys(render).length === 2;
}

function validateRelativeLeaf(relative) {
  if (
    typeof relative !== "string" || relative.length === 0
    || relative.includes("/") || relative.includes("\\")
    || relative === "." || relative === ".." || relative.includes("\0")
  ) throw officialPackageError("The bundled official skill manifest is invalid.");
}

function sameStringArray(left, right) {
  return Array.isArray(left)
    && Array.isArray(right)
    && left.length === right.length
    && left.every((value, index) => value === right[index]);
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function officialPackageError(message) {
  const error = new Error(message);
  error.code = "DOTAIOS_OFFICIAL_SKILL_PACKAGE_INVALID";
  return error;
}
