import fs from "node:fs/promises";
import path from "node:path";

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---/;

// Read one field out of a SKILL.md YAML frontmatter block. Deliberately tiny —
// skills only need `name` and `description`, both single-line scalars.
function readFrontmatterField(content, field) {
  const match = content.match(FRONTMATTER_RE);
  if (!match) return "";
  const line = match[1]
    .split(/\r?\n/)
    .find((entry) => entry.startsWith(`${field}:`));
  if (!line) return "";
  return line.slice(field.length + 1).trim().replace(/^["']|["']$/g, "");
}

function unquoteScalar(value) {
  return value.trim().replace(/^(['"])(.*)\1$/, "$2");
}

// Read either a comma-separated scalar or an indented YAML block list. Skill
// frontmatter only needs these two trigger shapes, so no YAML dependency is
// necessary.
function readFrontmatterList(content, field) {
  const frontmatter = content.match(FRONTMATTER_RE)?.[1];
  if (!frontmatter) return [];

  const lines = frontmatter.split(/\r?\n/);
  const fieldPattern = new RegExp(`^${field}:\\s*(.*)$`);
  const fieldIndex = lines.findIndex((line) => fieldPattern.test(line));
  if (fieldIndex === -1) return [];

  const inlineValue = lines[fieldIndex].match(fieldPattern)?.[1].trim();
  if (inlineValue) {
    return unquoteScalar(inlineValue).split(",").map(unquoteScalar).filter(Boolean);
  }

  const values = [];
  for (const line of lines.slice(fieldIndex + 1)) {
    if (!line.trim() || /^\s*#/.test(line)) continue;
    if (!/^\s/.test(line)) break;

    const item = line.match(/^\s+-\s+(.+?)\s*$/);
    if (!item) break;
    values.push(unquoteScalar(item[1]));
  }
  return values.filter(Boolean);
}

// Scan <aiosPath>/skills/ for every <name>/SKILL.md and return its metadata.
export async function collectSkills(aiosPath) {
  const skillsDir = path.join(aiosPath, "skills");
  let entries;
  try {
    entries = await fs.readdir(skillsDir, { withFileTypes: true });
  } catch {
    return [];
  }

  const skills = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".") || entry.name.startsWith("_")) continue;

    const skillFile = path.join(skillsDir, entry.name, "SKILL.md");
    let content;
    try {
      content = await fs.readFile(skillFile, "utf8");
    } catch {
      continue;
    }

    skills.push({
      dir: entry.name,
      name: readFrontmatterField(content, "name") || entry.name,
      description: readFrontmatterField(content, "description"),
      triggers: readFrontmatterList(content, "triggers")
    });
  }

  skills.sort((a, b) => a.name.localeCompare(b.name));
  return skills;
}

// Render the human- and agent-readable skills index.
export function renderSkillsIndex(skills) {
  const lines = [
    "# Installed Skills",
    "",
    "Auto-generated by DotAIOS. Do not edit by hand — it refreshes when you run",
    "`dotaios activate` or install/remove a skill.",
    "",
    "Skills are reusable workflows. **Any AI agent can run one**: open that",
    "skill's `SKILL.md` file and follow it. The user invokes a skill by name",
    "(for example: \"use the audit skill\" or \"run plan-today\").",
    "",
    "When the user seems stuck or asks what you can help with, suggest a relevant skill from this list.",
    ""
  ];

  if (skills.length === 0) {
    lines.push("_No skills installed yet. Add one with_ `dotaios skill add <url-or-path>`.", "");
  } else {
    for (const skill of skills) {
      lines.push(`## ${skill.name}`, "");
      if (skill.description) lines.push(skill.description, "");
      lines.push(`Run it: read \`skills/${skill.dir}/SKILL.md\` and follow the steps.`, "");
    }
  }

  return lines.join("\n");
}

// Escape a markdown table cell: pipes break columns, newlines break rows.
function escapeCell(value) {
  return String(value || "").replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

// Render the agent-facing routing table. The agent matches the user's intent to
// a row's trigger phrases, then opens that skill's SKILL.md. Skills without
// triggers fall back to their description. Plain text — the LLM does the match,
// no embeddings.
export function renderResolver(skills) {
  const lines = [
    "# Skill Resolver",
    "",
    "Auto-generated by DotAIOS. Do not edit by hand — it refreshes when you run",
    "`dotaios activate` or install/remove a skill.",
    "",
    "To handle a request, match the user's intent to a row below, then open that",
    "skill's `SKILL.md` and follow it. Prefer the most specific match. If nothing",
    "fits, fall back to `skills/INDEX.md`.",
    ""
  ];

  if (skills.length === 0) {
    lines.push("_No skills installed yet._", "");
    return lines.join("\n");
  }

  lines.push("| If the user wants… | Run this skill |", "| --- | --- |");
  for (const skill of skills) {
    const hints = skill.triggers && skill.triggers.length
      ? skill.triggers.join(" · ")
      : (skill.description || skill.name);
    lines.push(`| ${escapeCell(hints)} | \`skills/${skill.dir}/SKILL.md\` |`);
  }
  lines.push("");
  return lines.join("\n");
}

// Regenerate <aiosPath>/skills/RESOLVER.md from the skills currently on disk.
export async function writeResolver(aiosPath) {
  const skills = await collectSkills(aiosPath);
  const resolverPath = path.join(aiosPath, "skills", "RESOLVER.md");
  await fs.mkdir(path.dirname(resolverPath), { recursive: true });
  await fs.writeFile(resolverPath, `${renderResolver(skills)}\n`);
  return { path: resolverPath, count: skills.length };
}

// Regenerate the agent-facing skill files (INDEX.md + RESOLVER.md) from the
// skills currently on disk. Called after any operation that can change the
// installed skill set.
export async function writeSkillsIndex(aiosPath) {
  const skills = await collectSkills(aiosPath);
  const skillsDir = path.join(aiosPath, "skills");
  await fs.mkdir(skillsDir, { recursive: true });
  const indexPath = path.join(skillsDir, "INDEX.md");
  const resolverPath = path.join(skillsDir, "RESOLVER.md");
  await fs.writeFile(indexPath, `${renderSkillsIndex(skills)}\n`);
  await fs.writeFile(resolverPath, `${renderResolver(skills)}\n`);
  return { path: indexPath, resolverPath, count: skills.length };
}
