import fs from "node:fs/promises";
import path from "node:path";

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---/;

// Read one field out of a SKILL.md YAML frontmatter block. Deliberately tiny —
// skills only need `name` and `description`, both single-line scalars.
function readFrontmatterField(content, field) {
  const match = content.match(FRONTMATTER_RE);
  if (!match) return "";
  const line = match[1]
    .split(/\r?\n/)
    .find((entry) => entry.startsWith(`${field}:`));
  if (!line) return "";
  return line.slice(field.length + 1).trim().replace(/^["']|["']$/g, "");
}

// Scan <aiosPath>/skills/ for every <name>/SKILL.md and return its metadata.
export async function collectSkills(aiosPath) {
  const skillsDir = path.join(aiosPath, "skills");
  let entries;
  try {
    entries = await fs.readdir(skillsDir, { withFileTypes: true });
  } catch {
    return [];
  }

  const skills = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".") || entry.name.startsWith("_")) continue;

    const skillFile = path.join(skillsDir, entry.name, "SKILL.md");
    let content;
    try {
      content = await fs.readFile(skillFile, "utf8");
    } catch {
      continue;
    }

    skills.push({
      dir: entry.name,
      name: readFrontmatterField(content, "name") || entry.name,
      description: readFrontmatterField(content, "description")
    });
  }

  skills.sort((a, b) => a.name.localeCompare(b.name));
  return skills;
}

// Render the human- and agent-readable skills index.
export function renderSkillsIndex(skills) {
  const lines = [
    "# Installed Skills",
    "",
    "Auto-generated by DotAIOS. Do not edit by hand — it refreshes when you run",
    "`dotaios activate` or install/remove a skill.",
    "",
    "Skills are reusable workflows. **Any AI agent can run one**: open that",
    "skill's `SKILL.md` file and follow it. The user invokes a skill by name",
    "(for example \"run audit\" or \"/audit\").",
    ""
  ];

  if (skills.length === 0) {
    lines.push("_No skills installed yet. Add one with_ `dotaios skill add <url-or-path>`.", "");
  } else {
    for (const skill of skills) {
      lines.push(`## ${skill.name}`, "");
      if (skill.description) lines.push(skill.description, "");
      lines.push(`Run it: read \`skills/${skill.dir}/SKILL.md\` and follow the steps.`, "");
    }
  }

  return lines.join("\n");
}

// Regenerate <aiosPath>/skills/INDEX.md from the skills currently on disk.
// Called after any operation that can change the installed skill set.
export async function writeSkillsIndex(aiosPath) {
  const skills = await collectSkills(aiosPath);
  const indexPath = path.join(aiosPath, "skills", "INDEX.md");
  await fs.mkdir(path.dirname(indexPath), { recursive: true });
  await fs.writeFile(indexPath, `${renderSkillsIndex(skills)}\n`);
  return { path: indexPath, count: skills.length };
}
